### ISSUE TITLE
Duplicate declaration of Class[Apt]

### ISSUE THREAD

**Issue by HT43-bqxFqB** [puppet-community/puppet-unattended_upgrades#12]
When configuring an apt proxy with the puppetlabs/apt (2.0.0) module as
```
class {'::apt':
    proxy => {
        'host' => 'host',
        'port' => '3128',
    },
}
```

and configuring unattended_upgrades in parallel, one runs into
> Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Class[Apt] is already declared;

I would suspect that this [include](https://github.com/puppet-community/puppet-unattended_upgrades/blob/master/manifests/init.pp#L21) is the reason. As apt is allreday defined with our custom proxy settings...

**Comment by daenney** [comment]
Hmmm.... We don't really need the `include` there, it just made sense to have it but I can see why this goes wrong.

I can add an `if defined` check but that feels nasty. There's no way this module will ever work without the apt module so you might as well include it yourself...

This would work if you defined the options to `apt` in Hiera.

**Comment by daenney** [comment]
@mhaskel Opinion please!

**Comment by mhaskel** [comment]
-1 for if defined
+1 for adding a note in the README making it clear that you need to include apt for this to work

**Comment by HT43-bqxFqB** [comment]
Awesome, thanks for the fast response!

**Comment by daenney** [comment]
1.0.3 is on the Forge now which fixes the issue.

**Comment by mhaskel** [comment]
:+1:
