### ISSUE TITLE
potential dependency cycle for users

### ISSUE THREAD

**Issue by lexelby** [puppet-community/puppet-unattended_upgrades#16]
The 3 requires here could cause issues for users: https://github.com/puppet-community/puppet-unattended_upgrades/commit/886245f2cb7614a8c749d34e6f08ee17b92c970f#diff-60ae41fd0a31977447947f59940ee9a4R54

We ran into an issue where new hosts coming up couldn't find packages that were in our repo because the `apt-get update` wasn't running before packages were installed.  A solution would be something like this in site.pp:

    Class['apt::update'] -> Package <| |>

However, the requires here cause a dependency cycle if you do that.  apt::conf notifies Exec\['apt_update'\] (in apt::setting), so Package['unattended-upgrades'] gets chained before the apt update, but my spaceship operator up there wants to chain it after.

We ran into this problem with our own in-house unattended-upgrades module which had the exact same dependency (probably for the same reason :)).  The only way for a user of your module in our situation to work around this would be:

    Class['apt::update'] -> Package <| title != "unattended-upgrades" |>

which would work but is very hacky.

If you don't chain here, of course, you run the risk that the apt-periodic daily cron job runs after you've put down these config files but before the unattended-upgrades package is installed.  In practice, that's going to require some incredibly exact timing, and the result is just a failed cron job and not a failed puppet run.  We decided the risk was worthwhile.

It's occurred to us that perhaps we're doing something wrong with the above chaining, but we can't figure out what the "right" way to do it would be.  Any ideas?

**Comment by GhostLyrics** [comment]
If you do not find packages in your newly added repository, consider adding repositories (which afair triggers an `apt-get update`) in another puppet stage, before the main stage.

For example:

    stage{ 'initialization': before => Stage['main'] }

    node 'example'
    {
      class{ 'something::my_repo': stage => initialization}
      include other::stuff # install packages here
    }

**Comment by lexelby** [comment]
Thanks for your suggestion!

Unfortunately, it's not just a matter of new repos.  We publish new packages to our internal repo regularly.  Hosts that have been down or have not run puppet for a long time will also need to run apt-get update run to see the new packages before they can install them.

Our EC2 hosts are spun up using an AMI that was built using packer.  The AMI contains a filesystem on which a minimal run of puppet has already been performed, so all of our internal repos are already set up.  However, the host's apt cache is inevitably old because we only build new AMIs every few weeks.

Even not considering such edge cases, we'd run into this problem fairly often.  Any time we add a package to our repo and then try to puppet out manifests that add a package resource for that package, we'd need apt-get update to run before the package resource runs.

As far as I understand it, we can't use stages to cause the apt-get update to run before all package resources, because it would create a dependency cycle in just the same way that my chaining above would.

**Comment by GhostLyrics** [comment]
I could be overlooking an issue, but I think you might be able to use `puppetlabs/apt` to work around that:

    class { 'apt':
      update => {
        frequency => 'always',
      },
    }

I'd try putting this in a stage before main. (code example taken from the [puppetlabs/puppetlabs-apt docs](https://github.com/puppetlabs/puppetlabs-apt/tree/master#usage))

**Comment by bdellegrazie** [comment]
Just for reference, I've got exactly the same problem.

I've raised a defect against the puppetlabs/apt module as they should really expose the notify_update parameter of the apt::setting resource to the apt::conf module. - not every conf file install should result in triggering an apt-get update.

See: https://github.com/puppetlabs/puppetlabs-apt/pull/551

This module could use that facility (setting notify_update to false) to avoid triggering an apt-get update for the install of the conf files - in this case it is unnecessary.

Avoiding the notify of the update class removes the dependency cycle.

**Comment by fadenb** [comment]
We have the exactly same problem. Anyone found another workaround in the meantime until @bdellegrazie changes are merged into the apt module?

**Comment by bdellegrazie** [comment]
@fadenb FYI my changes were merged into the apt module upstream (master). It will be in the next release (2.1.1) whenever that is.

**Comment by igalic** [comment]
@bdellegrazie does that mean we can close this issue?

**Comment by bdellegrazie** [comment]
@igalic: as soon as puppetlabs-apt has its next release that includes the fix and the manifest here references that version, then the issue here can be closed.

**Comment by nibalizer** [comment]
@mhaskel do you know when you'll be releasing apt?

**Comment by mhaskel** [comment]
Hey @nibalizer, sorry, looks like we're trying to get an apt release out in the next week or two.

**Comment by nibalizer** [comment]
@mhaskel no worries! :)

**Comment by bdellegrazie** [comment]
@nibalizer FYI, new apt release is out (2.2.0) that contains the necessary fix

**Comment by igalic** [comment]
\o/ thanks everyone!
