### ISSUE TITLE
Not working on Ubuntu

### ISSUE THREAD

**Issue by leoarnold** [puppet-community/puppet-unattended_upgrades#22]
Ever since I upgraded from `puppetlabs-apt` v1.80 to v2.10 and `puppet-unattended_upgrades
` (this package) unattended upgrades stopped upgrading my clients completely. I checked the log file

    # /var/log/unattended-upgrades/unattended-upgrades.log
    2015-08-08 07:54:28,800 INFO Initial blacklisted packages:
    2015-08-08 07:54:28,800 INFO Starting unattended upgrades script
    2015-08-08 07:54:28,800 INFO Allowed origins are: ['o=Ubuntu,a={precise}-security', 'o=Ubuntu,a={precise}-updates']
    2015-08-08 07:54:33,790 INFO Packages that are auto removed: ''
    2015-08-08 07:54:33,791 INFO No packages found that can be upgraded unattended

and noticed the inappropriate curly braces in the origin `{precise}-security`. This is due to a critical typo in `params.pp` which causes invalid syntax in `/etc/apt/apt.conf.d/50unattended-upgrades`.

I will submit a pull request to fix this issue shortly.

**Comment by leoarnold** [comment]
I just noticed that this problem is known since pull request #14 which is stale since 24 days. So with this issue and pull request I would like to reassure you that this typo is the tried-and-tested single cause of the problem and it is preventing the package from achieving its number one mission objective. I suggest to merge and push to the forge soon to avoid customer dissatisfaction when more user start to upgrade their set-ups to `puppetlabs-apt` v2.x.x.

**Comment by cpick** [comment]
@igalic this issue should also be solved by the merging of #14 (as @leoarnold indicated above).
