### ISSUE TITLE
No way to define different keys for "auto" in different hiera sources

### ISSUE THREAD

**Issue by sdelafond** [puppet-community/puppet-unattended_upgrades#35]
I'd like to have a merge behavior by default, using the following hierarchy:

common.yaml
```
unattended_upgrades::auto:
  remove: false
  reboot: true
```

nodes/foo.yaml
```
unattended_upgrades::auto:
  reboot: false
```

Unfortunately, hiera_hash() isn't used  for the auto parameter, so we end with the default priority lookup instead, and "remove:false" isn't used on node foo.

**Comment by igalic** [comment]
since this is a puppet """""""feature"""""", the only way to fix that is either repeat yourself, or wrap this class into a profile.

:( closing this, as "can't fix" ):

**Comment by sdelafond** [comment]
It believe it can be fixed: this behavior is just the default for automatic parameter lookup. How about something along those lines ? https://www.sidorenko.io/blog/2014/07/05/puppet-hiera-hash-merge-and-automatic-parameter-lookup/

**Comment by sdelafond** [comment]
Does this not sound like an acceptable solution ?

**Comment by daenney** [comment]
That would explicitly require us to add all the `hiera_hash()` calls in a bunch of places and not everyone might even be needing it, meaning more things to check and more special cases to deal with.

What you want can be achieved by changing Hiera's Hash merge behaviour: http://docs.puppetlabs.com/hiera/3.0/configuring.html#mergebehavior
